---
lan_interface: "wlan0"
lan2_interface: "wlxe0d3629774f7"

lan_ssid: "Firewall-5G"
lan2_ssid: "Firewall-2.4G"

lan_passphrase: "password"
lan2_passphrase: "password"

lan_ip: "172.16.0.1"
lan2_ip: "192.168.0.1"

country_code: "GB"