---
# - name: Install iptables-persistent
#   apt:
#     name:
#       - iptables-persistent
#     update_cache: yes

- name: Create config directory
  file:
    dest: /etc/iptables/
    state: directory
    mode: '0755'

- name: Deploy iptables configs
  template:
    src: "{{ item }}.j2"
    dest: /etc/iptables/{{ item }}
  loop:
    - class-a
    - class-b
    - class-c
  
- name: Apply class-a rules (with a policy reset)
  shell: iptables-restore < /etc/iptables/class-a

- name: Apply class-b and class-c rules (TO APPEND)
  shell: iptables-restore -n < /etc/iptables/{{ item }}
  loop:
    - class-b
    - class-c
