---
dns_servers:
  - "8.8.8.8"
  - "1.1.1.1"

wan_interface: "eth0"
lan_interface: "wlan0"
lan2_interface: "wlx1cbfce8347d0"

wan_prefix: "8"
wan_gateway: "10.0.0.1"

lan_ip: "172.16.0.1"
lan_prefix: "16"

lan2_ip: "192.168.0.1"
lan2_prefix: "24"

netplan_config_file: "/etc/netplan/50-cloud-init.yaml"