---
- name: Install hostapd
  apt:
    name: hostapd
    state: present
    update_cache: yes

- name: Stop and disable default hostapd service
  systemd:
    name: hostapd.service
    state: stopped
    enabled: no
    masked: yes

- name: Deploy LAN hostapd configuration
  template:
    src: hostapd-lan.conf.j2
    dest: /etc/hostapd/hostapd-lan.conf
    mode: '0600'
  notify: restart hostapd-lan

- name: Deploy LAN2 hostapd configuration
  template:
    src: hostapd-lan2.conf.j2
    dest: /etc/hostapd/hostapd-lan2.conf
    mode: '0600'
  notify: restart hostapd-lan2

- name: Deploy LAN hostapd systemd service
  copy:
    src: hostapd-lan.service
    dest: /etc/systemd/system/hostapd-lan.service
    mode: '0644'
  notify: 
    - daemon reload
    - restart hostapd-lan

- name: Deploy LAN2 hostapd systemd service
  copy:
    src: hostapd-lan2.service
    dest: /etc/systemd/system/hostapd-lan2.service
    mode: '0644'
  notify:
    - daemon reload
    - restart hostapd-lan2

- name: Enable hostapd services
  systemd:
    name: "{{ item }}"
    enabled: yes
    daemon_reload: yes
  loop:
    - hostapd-lan.service
    - hostapd-lan2.service

- name: Start hostapd services
  systemd:
    name: "{{ item }}"
    state: started
  loop:
    - hostapd-lan.service
    - hostapd-lan2.service